### ISSUE TITLE
User feed serving

### ISSUE THREAD

**Issue by komal-sai-yral** [yral-dapp/off-chain-agent#32]
- [x] go-bazzinga/hot-or-not-backend-canister#347
- [x] go-bazzinga/off-chain-agent#37
- [x] go-bazzinga/hot-or-not-web-leptos-ssr#261

1. on chain (2 days)
	1. apis to store view history and successful plays
	2. logic to refresh view history and successful plays

```
// Format for data in canisters
pub struct WatchHistoryItem {
    post_id: u64,
    publisher_canister_id: Principal,
    viewed_at: SystemTime,
    cf_video_id: String,
    percentage_watched: f32,
}

pub struct SuccessHistoryItem {
    post_id: u64,
    publisher_canister_id: Principal,
    interacted_at: SystemTime,
    cf_video_id: String,
}

```

2. Off chain agent (2-3 days)
	1. logic to push success and view data onchain
	2. push to upstash queue 

3. FE (5 days)
	1. Fetch next list of videos after N (?) watches
	2. Fallback to calling postcache if above fails
	3. proper testing

**Comment by harshitasrivastav28** [comment]
Next step:

Abhishek's cannister update to go today and Komal's to go tomorrow.
Komal has started working on frontend side.

**Comment by harshitasrivastav28** [comment]
- Monday EOD we should have a staging link for testing

**Comment by Natasha-GB** [comment]
- Logic on FE completed

**Comment by Natasha-GB** [comment]
- hotornot.wtf changes need to be incorporated
- Conditional logic based on env var (separate task) @Natasha-GB 
- Use feature flag for an isolated module/release via A/B testing

**Comment by Natasha-GB** [comment]
- Timestamp metadata

**Comment by Natasha-GB** [comment]
- Timestamp added already

**Comment by harshitasrivastav28** [comment]
- Auth needs to be changed
- By tomorrow EOD we should be able to merge it

**Comment by Natasha-GB** [comment]
- FE changes done, PR will be raised today
- Should be able to deploy tomorrow

**Comment by harshitasrivastav28** [comment]
- ML feed has been merged into main

**Comment by harshitasrivastav28** [comment]
- We are good to deploy the ML feed on HOT or NOT wtf.
- We will need to plan for traffic on HOT or NOT.wtf
- Event segregation for YRAL and HON.wtf is to be done

**Comment by Natasha-GB** [comment]
- Hotornot.wtf connection done
- Event segregation to be worked on
